### ISSUE TITLE
unable to make algosec_provision_network_connectivity module work.

### ISSUE THREAD

**Issue by RoxyLovesToCode** [algosec/algosec-ansible-role#19]
Hi.

Ive just installled this role on my workstation. the only thing i have changed is username and password. and algosec ip address in the inventory file. the rest is the playbook from the example. 

This is the error i recieve
The full traceback is:
Traceback (most recent call last):
  File "/home/shirtclr/.ansible/tmp/ansible-tmp-1615766010.680147-26541-162411853222896/AnsiballZ_algosec_provision_network_connectivity.py", line 102, in <module>
    _ansiballz_main()
  File "/home/shirtclr/.ansible/tmp/ansible-tmp-1615766010.680147-26541-162411853222896/AnsiballZ_algosec_provision_network_connectivity.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/shirtclr/.ansible/tmp/ansible-tmp-1615766010.680147-26541-162411853222896/AnsiballZ_algosec_provision_network_connectivity.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible.modules.algosec_provision_network_connectivity', init_globals=None, run_name='__main__', alter_sys=True)
  File "/usr/lib64/python3.6/runpy.py", line 205, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_algosec_provision_network_connectivity_payload_xm2szyga/ansible_algosec_provision_network_connectivity_payload.zip/ansible/modules/algosec_provision_network_connectivity.py", line 139, in <module>
  File "/tmp/ansible_algosec_provision_network_connectivity_payload_xm2szyga/ansible_algosec_provision_network_connectivity_payload.zip/ansible/modules/algosec_provision_network_connectivity.py", line 52, in main
  File "/tmp/ansible_algosec_provision_network_connectivity_payload_xm2szyga/ansible_algosec_provision_network_connectivity_payload.zip/ansible/modules/algosec_provision_network_connectivity.py", line 25, in __init__
TypeError: object.__init__() takes no parameters
fatal: [10.52.194.30]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/home/shirtclr/.ansible/tmp/ansible-tmp-1615766010.680147-26541-162411853222896/AnsiballZ_algosec_provision_network_connectivity.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/home/shirtclr/.ansible/tmp/ansible-tmp-1615766010.680147-26541-162411853222896/AnsiballZ_algosec_provision_network_connectivity.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/shirtclr/.ansible/tmp/ansible-tmp-1615766010.680147-26541-162411853222896/AnsiballZ_algosec_provision_network_connectivity.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible.modules.algosec_provision_network_connectivity', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/lib64/python3.6/runpy.py\", line 205, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib64/python3.6/runpy.py\", line 96, in _run_module_code\n    mod_name, mod_spec, pkg_name, script_name)\n  File \"/usr/lib64/python3.6/runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_algosec_provision_network_connectivity_payload_xm2szyga/ansible_algosec_provision_network_connectivity_payload.zip/ansible/modules/algosec_provision_network_connectivity.py\", line 139, in <module>\n  File \"/tmp/ansible_algosec_provision_network_connectivity_payload_xm2szyga/ansible_algosec_provision_network_connectivity_payload.zip/ansible/modules/algosec_provision_network_connectivity.py\", line 52, in main\n  File \"/tmp/ansible_algosec_provision_network_connectivity_payload_xm2szyga/ansible_algosec_provision_network_connectivity_payload.zip/ansible/modules/algosec_provision_network_connectivity.py\", line 25, in __init__\nTypeError: object.__init__() takes no parameters\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}

Any help would be appreciated

**Comment by libermandovev** [comment]
Hello @RoxyLovesToCode please see #20 as a probably fix to the issue you reported
